name: Books Python

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
              image: mysql
              ports:
                - 3306:3306
              options: >-
                --health-cmd="mysqladmin ping --silent"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=3
              env:
                MYSQL_ROOT_PASSWORD: admin
                MYSQL_DATABASE: BookInventory
        steps:
            - name: Hacer checkout del proyecto
              uses: actions/checkout@v4

            - name: Configurar python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' 

            - name: Instalar dependencias
              run: pip install -r requirements.txt

            - name: Ejecucion de Pruebas
              env:
                SQLALCHEMY_DATABASE_URI: "mysql+mysqlconnector://root:admin@localhost:3306/BookInventory"
              run: pytest app_test.py --cov

            - name: Mostrar mensaje de éxito
              run: echo "Exito en todas las Acciones"